import { create } from "zustand";
import axios from "axios";

const API_URL = "http://localhost:2200/transactions";

const useTransactionStore = create((set) => ({
  transactions: [],

  // fetch transaction
  fetchTransactions: async () => {
    try {
      const response = await axios.get(API_URL);
      set({ transactions: response.data });
    } catch (error) {
      console.error("Error fetching transactions", error);
    }
  },

  // Store transaction history
  saveTransaction: async (transactionDetail) => {
    try {
      // Don't include `transactionId` since it's being generated by the backend
      const { transactionId, ...transactionData } = transactionDetail;

      console.log("Saving transaction:", transactionData);  // Log transaction data before sending it

      // ✅ Send the transaction data directly
      const response = await axios.post(API_URL, transactionDetail);


      set((state) => ({
        transactions: [...state.transactions, response.data],
      }));
    } catch (error) {
      console.error(
        "Error saving transaction:",
        error.response?.data || error.message
      );
    }
  },



}));

export default useTransactionStore;
